[package]
name = "alpaca"
version = "0.1.0"
authors = [
  "Giovanni Cherubin <g.chers@gmail.com>",
  "Noah Vesely <fowlslegs@riseup.net>",
]

[lib]
name = "alpaca"
crate-type = ["rlib", "dylib"]

[dependencies]
rand = "0.4.2"
select = "0.4.2"
url = "1.6.0"
